name: tests
on:
  schedule:
    # At 12:55 every Saturday
    - cron:  '55 12 * * 6'
jobs:
  refresh_nameservers:
    runs-on: ubuntu-latest
    needs: lint
    # if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Refresh nameservers.txt
        run: poetry run python public_dns_servers/clean_nameservers.py
      - name: git add nameservers.txt
        uses: EndBug/add-and-commit@v9
        with:
          add: "nameservers.txt"
          default_author: github_actions
          message: "refresh nameservers.txt"
